Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
#  config.vm.box = "bento/centos-7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
  end

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.network "private_network", ip: "172.28.128.50"

    jenkins.vm.provision "shell", inline: <<-SHELL
      curl -o /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
      rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      yum install -y jenkins maven git ansible wget java-1.8.0-openjdk
      service jenkins start
      echo "172.28.128.51 gitrepo" >> /etc/hosts
      echo "172.28.128.52 nexus" >> /etc/hosts
    SHELL

  end

  config.vm.define "gitrepo" do |gitrepo|
    gitrepo.vm.network "forwarded_port", guest: 22, host: 2300
    gitrepo.vm.network "private_network", ip: "172.28.128.51"

    gitrepo.vm.provision "shell", inline: <<-SHELL
      yum install -y git
      useradd git
      sudo -u git bash -c "cd /home/git && mkdir repos .ssh"
      sudo -u git bash -c "cd /home/git/.ssh && cp /vagrant/ssh-keys/authorized_keys . && chmod 444 authorized_keys"
      sudo -u git bash -c "cd /home/git/repos && git init --bare demo && git init --bare jobdsl && git init --bare ansible"
    SHELL

  end

  config.vm.define "nexus" do |nexus|
    nexus.vm.network "forwarded_port", guest: 8081, host: 8081
    nexus.vm.network "private_network", ip: "172.28.128.52"

    nexus.vm.provision "shell", inline: <<-SHELL
      yum install -y java-1.8.0-openjdk
      curl -L -o /tmp/nexus.tar.gz https://download.sonatype.com/nexus/3/latest-unix.tar.gz
      (cd /opt && tar xvzf /tmp/nexus.tar.gz)
      ln -s /opt/nexus* /opt/nexus
      cp /vagrant/service/nexus.service /etc/systemd/system/
      systemctl daemon-reload
      systemctl enable nexus.service
      systemctl start nexus.service
    SHELL

  end

end
